
### 获取用户信息
POST http://localhost:8082/ubprc/
Content-Type: application/json

{
  "service": "io.unbong.ubrpc.demo.api.UserService",
  "methodSign": "findById@1_int",
  "args": [100]
}

### 获取订单信息
POST http://localhost:8081/ubprc/
Content-Type: application/json

{
  "service": "io.unbong.ubrpc.demo.api.UserService",
  "methodSign": "findById@1_int",
  "args": [200]
}

### mock2
POST http://localhost:8080
Content-Type: application/json

{
  "service": "io.unbong.ubrpc.demo.api.UserService",
  "methodSign": "hashCode@0",
  "args": []
}

### get findById
GET http://localhost:8088/?id=100

### get set gray ratio
GET http://localhost:8088/garay/?ratio=100


### find timeout
GET http://localhost:8088/find/?timeout=1100
### port 修改 fortest
GET http://localhost:8081/ports?ports=8080.8094


### test
GET http://localhost:8088/test/
