server:
  port: 8081
ubrpc:
  zkServer: localhost:12181
  zkRoot: Ubrpc


app:
  id: app1
  namespace: public
  env: dev
  metas:  "{dc: 'bj', gray: 'false', unit: 'B001' }"


logging:
  level:
    root: info
    io.unbong: debug
apollo:
  cache-dir: /opt/data/
  cluster: default
  meta: http://localhost:8080
  autoUpdateInjectedSpringProperties: true
  bootstrap:
    enabled: true
    namespaces: app3
    eagerLoad:
      enabled: false


ubregistry:
  servers: http://localhost:8484
